### ISSUE TITLE
repository is empty

### ISSUE THREAD

**Issue by chee** [0xtob/libntxm#1]
hey! i was going to try building nitrotracker locally with the newest devkitpro, and i'm installing the required libs. This is one of them, but the repo is empty! i guess google code messed up the export?

**Comment by chee** [comment]
it doesn't have any history, because i don't think google code is running subversion or the export-to-github script anymore, but here is the library (from the latest 0.2 archive available on google code) if anyone needs it:

https://github.com/chee/libntxm

**Comment by 0xtob** [comment]
Indeed, looks like the export failed! Thanks for importing the lib to Github. I'll delete this repo and fork your version.
